/*
 * Copyright 2017 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.github.wonwoo.dynamodb.autoconfigure;

import static org.assertj.core.api.Assertions.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.BDDMockito.*;

import java.util.Collections;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.Mock;
import org.mockito.junit.MockitoJUnitRunner;
import org.springframework.data.annotation.Id;

import com.amazonaws.AmazonClientException;
import com.amazonaws.services.dynamodbv2.AmazonDynamoDB;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.model.CreateTableRequest;
import com.amazonaws.services.dynamodbv2.model.CreateTableResult;
import com.amazonaws.services.dynamodbv2.model.DescribeTableRequest;
import com.amazonaws.services.dynamodbv2.model.DescribeTableResult;
import com.amazonaws.services.dynamodbv2.model.ListTablesResult;
import com.amazonaws.services.dynamodbv2.model.ResourceNotFoundException;
import com.amazonaws.services.dynamodbv2.model.TableDescription;
import com.amazonaws.services.dynamodbv2.model.TableStatus;
import com.amazonaws.services.dynamodbv2.util.TableUtils.TableNeverTransitionedToStateException;

/**
 * @author wonwoo
 */
@RunWith(MockitoJUnitRunner.class)
public class DynamoDbCreateTableTests {

  @Mock
  private AmazonDynamoDB amazonDynamoDB;

  private DynamoDbCreateTable dynamoDbCreateTable;

  @Before
  public void setup() {
    this.dynamoDbCreateTable = new DynamoDbCreateTable(this.amazonDynamoDB);
  }


  @Test
  public void isFoundTable() {
    final ListTablesResult listTablesResult = new ListTablesResult();
    listTablesResult.setTableNames(Collections.singleton("persons"));
    given(amazonDynamoDB.listTables()).willReturn(listTablesResult);
    assertThat(dynamoDbCreateTable.isTable("persons")).isTrue();
  }

  @Test
  public void isNotFoundTable() {
    final ListTablesResult listTablesResult = new ListTablesResult();
    listTablesResult.setTableNames(Collections.singleton("persons"));
    given(amazonDynamoDB.listTables()).willReturn(listTablesResult);
    assertThat(dynamoDbCreateTable.isTable("foo")).isFalse();
  }

  @Test
  public void createTable() {
    final CreateTableResult createTableResult = new CreateTableResult();
    final TableDescription tableDescription = new TableDescription();
    tableDescription.setTableStatus(TableStatus.CREATING);
    createTableResult.setTableDescription(tableDescription);
    given(amazonDynamoDB.createTable(any(CreateTableRequest.class)))
        .willReturn(createTableResult);
    final CreateTableResult table =
        dynamoDbCreateTable.createTable(TestTable.class);
    assertThat(table.getTableDescription().getTableStatus()).isEqualTo("CREATING");
  }

  @Test
  public void waitTableExistsTrueTest() {
    given(this.amazonDynamoDB.describeTable(any(DescribeTableRequest.class)))
        .willAnswer(invocation -> describeTableResult(TableStatus.CREATING))
        .willAnswer(invocation -> describeTableResult(TableStatus.CREATING))
        .willReturn(describeTableResult(TableStatus.ACTIVE));
    dynamoDbCreateTable.waitTableActive("test", 30, 5);
    // no exception should be thrown
  }


  @Test
  public void waitTableResourceNotFoundExceptionTest() {
    given(this.amazonDynamoDB.describeTable(any(DescribeTableRequest.class)))
        .willThrow(new ResourceNotFoundException("table Not Found"))
        .willReturn(describeTableResult(TableStatus.ACTIVE));
    dynamoDbCreateTable.waitTableActive("test", 10, 5);
    // no exception should be thrown
  }


  @Test(expected = AmazonClientException.class)
  public void waitTableIllegalStateExceptionTest() {
    given(this.amazonDynamoDB.describeTable(any(DescribeTableRequest.class)))
        .willAnswer(invocation -> describeTableResult(TableStatus.CREATING))
        .willThrow(new AmazonClientException("error"));
    dynamoDbCreateTable.waitTableActive("test", 10, 5);
  }

  @Test(expected = TableNeverTransitionedToStateException.class)
  public void waitTableExistsFalseTest() {
    given(this.amazonDynamoDB.describeTable(any(DescribeTableRequest.class)))
        .willAnswer(invocation -> describeTableResult(TableStatus.CREATING))
        .willAnswer(invocation -> describeTableResult(TableStatus.CREATING))
        .willAnswer(invocation -> describeTableResult(TableStatus.CREATING))
        .willReturn(describeTableResult(TableStatus.ACTIVE));
    dynamoDbCreateTable.waitTableActive("test", 10, 5);
  }

  private DescribeTableResult describeTableResult(final TableStatus tableStatus) {
    final DescribeTableResult describeTableResult = new DescribeTableResult();
    final TableDescription tableDescription = new TableDescription();
    tableDescription.setTableStatus(tableStatus);
    describeTableResult.setTable(tableDescription);
    return describeTableResult;
  }

  @DynamoDBTable(tableName = "test")
  private static class TestTable {
    @Id
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBIndexHashKey(globalSecondaryIndexName = "idx_test_indexedField")
    private int indexedField;

    public String getId() {
        return id;
    }

    public void setId(final String id) {
        this.id = id;
    }

    public int getIndexedField() {
        return indexedField;
    }

    public void setIndexedField(final int indexedField) {
        this.indexedField = indexedField;
    }

  }
}
